# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TrycariOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TrycariOS
        pod 'RxSwift', '~> 5'
   	    pod 'RxCocoa', '~> 5'
        pod 'Alamofire', '~> 5.2'
        pod 'ReachabilitySwift'

  target 'TrycariOSTests' do
    inherit! :search_paths
        pod 'RxBlocking', '~> 5'
        pod 'RxTest', '~> 5'
  end

  target 'TrycariOSUITests' do
        # Pods for testing
  end

end
